auth_enabled: false

server:
  http_listen_address: 0.0.0.0
  grpc_listen_address: 0.0.0.0
  http_listen_port: 3100
  grpc_listen_port: 9095
  log_level: info

common:
  path_prefix: /tmp/loki
  storage:
    s3:
      endpoint: minio:9000
      insecure: true
      bucketnames: loki-data
      access_key_id: loki
      secret_access_key: supersecret
      s3forcepathstyle: true
  ring:
    instance_addr: 0.0.0.0
    kvstore:
      store: inmemory
  # storage:
  #   filesystem:
  #     chunks_directory: /tmp/loki/chunks
  #     rules_directory: /tmp/loki/rules
  # replication_factor: 1
  # ring:
  #   instance_addr: 127.0.0.1
  #   kvstore:
  #     store: inmemory

schema_config:
  configs:
    - from: 2021-08-01
      store: boltdb-shipper
      object_store: s3
      schema: v11
      index:
        prefix: index_
        period: 24h
  # configs:
  #   - from: 2020-10-24
  #     store: boltdb-shipper
  #     object_store: filesystem
  #     schema: v11
  #     index:
  #       prefix: index_
  #       period: 24h

limits_config:
  ingestion_rate_mb: 1024
  ingestion_burst_size_mb: 1024

ruler:
  alertmanager_url: http://localhost:9093
  storage:
    s3:
      bucketnames: loki-ruler
